from .script import Script
from ..utils.errors import ParserError


class Mdp(Script):

    def __init__(self, **kwargs):

        super().__init__(**kwargs)

        if 'title' in kwargs:
            self.name = kwargs['title']

        if not self.hasparam('name'):
            self.name = 'MD Run'

    def edit(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def __str__(self):
        val = f'; Gromacs MD parameters for {self.name} generated by MiMiCPy\n'

        for d in self.params():
            if d == 'name':
                continue

            if getattr(self, d) == None:
                continue

            d_ = d.replace('_', '-')
            val += f"{d_} = {getattr(self, d)}\n"

        return val

    @classmethod
    def from_text(cls, text):
        kwargs = {}
        for i, line in enumerate(text.splitlines()):
            line = line.strip()
            if line.startswith(';'): continue
            vals = line.split(';')[0].split('=')
            if len(vals) < 2:
                raise ParserError(file_type='mdp', line_number=i)
            param, val = vals
            kwargs.update({param.strip(): val.strip()})
        return cls(**kwargs)
