class MDP:
    def __init__(self, **kwargs):
        
        for key, value in kwargs.items():
            setattr(self, key, value)
        
        if self.name is None and self.title is None:
            self.name = 'JOB'
        
    def __str__(self):
        if self.title and not self.name: self.name = self.title

        val = f'; Gromacs MD parameters for {self.name} run\n; Generated by pygmx\n'
        
        data = [attr for attr in dir(self) if not callable(getattr(self, attr)) and attr[:2] != '__' and attr != 'name']
        
        for d in data:
            if getattr(self, d) == None:
                continue
            
            d_ = d.replace('_','-')
            val += f"{d_} = {getattr(self, d)}\n"
        
        return val
    
    @classmethod
    def defaultGenion(cls):
        return cls(name = 'Genion',
        integrator = "steep",  # Algorithm (steep = steepest descent minimization)
        emtol = 1000.0, # Stop minimization when the maximum force < 1000.0 kJ/mol/nm
        emstep = 0.01,  # Minimization step size
         nsteps = 50000, # Maximum number of (minimization) steps to perform
        nstlist = 10, # Frequency to update the neighbor list and long range forces
         cutoff_scheme = "Verlet", # Buffered neighbor searching 
         ns_type = "grid", # Method to determine neighbor list (simple, grid)
         coulombtype = "cutoff", #Treatment of long range electrostatic interactions
         rcoulomb = 1.0,# Short-range electrostatic cut-off
          rvdw = 1.0, # Short-range Van der Waals cut-off
          pbc = 'xyz')
        
    @classmethod
    def defaultEM(cls):
        em = cls.defaultGenion()
        em.name = 'Minim'
        em.coulombtype = "PME"
        return em
    
    @classmethod
    def defaultNVT(cls):
        return cls(name = 'NVT', 
                   define = '-DPOSRES',  # position restrain the protein
                   # Run parameters
                   integrator = 'md', #leap-frog integrator
                   nsteps = 50000, # 2 * 50000 = 100 ps
                   dt = 0.002, #2 fs
                   # Output control
                   nstxout = 500, # save coordinates every 1.0 ps
                   nstvout = 500, # save velocities every 1.0 ps
                   nstenergy = 500, # save energies every 1.0 ps
                   nstlog = 500, # update log file every 1.0 ps
                   #Bond parameters
                   continuation = 'no', # first dynamics run
                   constraint_algorithm = 'lincs', # holonomic constraints 
                   constraints = 'h_bonds', # bonds involving H are constrained
                   lincs_iter = 1, # accuracy of LINCS
                   lincs_order = 4, # also related to accuracy
                   # Nonbonded settings 
                   cutoff_scheme = 'Verlet', # Buffered neighbor searching
                   ns_type = 'grid', # search neighboring grid cells
                   nstlist = 10, # largely irrelevant with Verlet
                   rcoulomb = 1.0, # short-range electrostatic cutoff (in nm)
                   rvdw = 1.0, # short-range van der Waals cutoff (in nm)
                   DispCorr = 'EnerPres', # account for cut-off vdW scheme
                   # Electrostatics
                   coulombtype = 'PME', # Particle Mesh Ewald for long-range electrostatics
                   pme_order   = 4, # cubic interpolation
                   fourierspacing = 0.16, # grid spacing for FFT
                   # Temperature coupling is on
                   tcoupl = 'V-rescale', # modified Berendsen thermostat
                   tc_grps = 'Protein Non-Protein', # two coupling groups - more accurate
                   tau_t = '0.1     0.1', # time constant, in ps
                   ref_t = '300     300', # reference temperature, one for each group, in K
                   # Pressure coupling is off
                   pcoupl = 'no', # no pressure coupling in NVT
                   # Periodic boundary conditions
                   pbc    = 'xyz', # 3-D PBC
                   # Velocity generation
                   gen_vel = 'yes', # assign velocities from Maxwell distribution
                   gen_temp = 300, # temperature for Maxwell distribution
                   gen_seed = -1, # generate a random seed
                   )
    @classmethod   
    def defaultNPT(cls):
        npt = cls.defaultNVT()
        npt.name = 'NPT'
        npt.continuation = 'yes'
        npt.pcoupl = 'Parrinello-Rahman' # Pressure coupling on in NPT
        npt.pcoupltype = 'isotropic' # uniform scaling of box vectors
        npt.tau_p = 2.0 # time constant, in ps
        npt.ref_p = 1.0  # reference pressure, in bar
        npt.compressibility = '4.5e-5' # isothermal compressibility of water, bar^-1
        npt.refcoord_scaling = 'com'
        npt.DispCorr = 'EnerPres' # account for cut-off vdW scheme
        # Periodic boundary conditions
        npt.pbc = 'xyz' # 3_D PBC
        # Velocity generation
        npt.gen_vel = 'no' # Velocity generation is off 
        npt.gen_vel = None
        npt.gen_temp = None
        npt.gen_seed = None
        
        return npt
     
    @classmethod
    def defaultEQMD(cls):
        eq = cls.defaultNPT()
        eq.name = 'EQMD'
        eq.define = None
        eq.nstxout = 10000 # reduced frequency of.trr file by specifying 
        eq.nstvout = 0 # 10000 for output frequency of nstxout,
        eq.nstfout = 0 # nstvout, and nstfout are 0 frequency
        eq.nstenergy = 5000 # save energies every 10.0 ps
        eq.nstlog  = 5000 # update log file every 10.0 ps
        eq.nstxout_compressed = 5000 # save compressed coordinates every 10.0 ps
        eq.compressed_x_grps = 'System' # save the whole system
        eq.refcoord_scaling = None

        return eq
